/* LP Note — standalone, dependency-free, browser-local workspace */
'use strict';
const C=window.LP,KEY='osanai-lp-note-v1',$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yen=v=>v===null?'—':'¥'+Math.round(v).toLocaleString('ja-JP'),num=v=>Number(v).toLocaleString('ja-JP'),pct=v=>v===null?'—':v.toLocaleString('ja-JP',{maximumFractionDigits:2})+'%';
const metricLabels={spend:'広告費',clicks:'クリック数',visits:'送客数',conversions:'成果数',revenue:'売上',other:'その他費用',profit:'利益',cpv:'送客単価',cpa:'成果単価（CPA）',cpc:'クリック単価',cvr:'CVR',roas:'ROAS',sendRate:'送客率',closeRate:'送客後成約率',margin:'利益率'};
const fmt=(k,v)=>['cvr','roas','sendRate','closeRate','margin'].includes(k)?pct(v):['clicks','visits','conversions','days'].includes(k)?num(v):yen(v);
let actual=C.empty(),raw=null,blocked=false,demo=false,data=actual,view='dashboard',selected='',selectedVersion='',windowDays=7,rankMetric='profit',search='',formState=null,confirmResolve=null;
function load(){try{raw=localStorage.getItem(KEY);actual=raw?C.validate(JSON.parse(raw)):C.empty();blocked=false;$('#storage-alert').hidden=true;}catch{blocked=true;$('#storage-alert').hidden=false;$('#storage-alert').textContent='保存データを読み込めません。元データは変更していません。バックアップから復元するか、元データを書き出して保管してください。';}data=demo?C.sample():actual;}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
async function save(next,recover=false){if(demo)throw Error('サンプル表示中は保存できません。');if(blocked&&!recover)throw Error('保存を停止しています。上部の案内に従って再読み込み、またはバックアップから復元してください。');C.validate(next);const write=()=>{if(localStorage.getItem(KEY)!==raw)throw Error('別タブで更新されました。再読み込みしてからやり直してください。');const output=JSON.stringify(next);try{localStorage.setItem(KEY,output);}catch{throw Error('保存できませんでした。ブラウザの保存容量・設定を確認してください。入力内容は画面に残っています。');}raw=output;actual=next;data=actual;blocked=false;$('#storage-alert').hidden=true;};if(navigator.locks)await navigator.locks.request(KEY,write);else write();render();}
const clone=()=>JSON.parse(JSON.stringify(actual));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const lpName=id=>data.lps.find(l=>l.id===id)?.name||'不明';
function confirmAction(message,title='確認'){return new Promise(resolve=>{confirmResolve=resolve;$('#confirm-title').textContent=title;$('#confirm-message').textContent=message;$('#confirm').showModal();$('#confirm-no').focus();});}
function endConfirm(v){$('#confirm').close();confirmResolve?.(v);confirmResolve=null;}
$('#confirm-no').onclick=()=>endConfirm(false);$('#confirm-yes').onclick=()=>endConfirm(true);$('#confirm').addEventListener('cancel',e=>{e.preventDefault();endConfirm(false);});
function range(){const t=C.today(),p=$('#period').value;if(p==='all')return ['2000-01-01','2099-12-31'];if(p==='today')return [t,t];if(p==='yesterday')return [C.shift(t,-1),C.shift(t,-1)];if(p==='custom')return [$('#start').value,$('#end').value];const first=t.slice(0,7)+'-01';if(p==='last'){const end=C.shift(first,-1);return [end.slice(0,7)+'-01',end];}return [first,t];}
function filtered(){const [a,b]=range(),id=$('#lp-filter').value;if(!C.day(a)||!C.day(b)||a>b)return [];return data.records.filter(r=>r.date>=a&&r.date<=b&&(!id||r.lpId===id));}
function totalsByLP(){const rows=filtered(),id=$('#lp-filter').value;return data.lps.filter(l=>!id||l.id===id).map(l=>({...l,...C.sum(rows.filter(r=>r.lpId===l.id))}));}
function ranked(){const asc=['cpv','cpa','cpc'].includes(rankMetric);return totalsByLP().sort((a,b)=>{const av=a.days?a[rankMetric]:null,bv=b.days?b[rankMetric]:null;if(av===null)return bv===null?0:1;if(bv===null)return -1;return asc?av-bv:bv-av;});}
function empty(title,body,button='add-lp',label='＋ 最初のLPを登録'){return `<div class="panel empty"><div class="empty-icon">↗</div><h2>${title}</h2><p>${body}</p><button class="primary" data-action="${button}">${label}</button>${!demo?'<button data-action="demo">サンプルを見る</button>':''}</div>`;}
function kpis(t){const subs={spend:'送客単価 '+yen(t.cpv),clicks:'クリック単価 '+yen(t.cpc),visits:'送客率 '+pct(t.sendRate),conversions:'CVR '+pct(t.cvr),revenue:'ROAS '+pct(t.roas),profit:'売上 − 広告費 − その他費用'};return `<div class="kpis">${['spend','clicks','visits','conversions','revenue','profit'].map(k=>`<div class="kpi ${k==='profit'?'highlight':''} ${k==='profit'&&t[k]<0?'negative':''}"><div class="kpi-label">${metricLabels[k]}${k==='profit'&&t[k]<0?' · 赤字':''}</div><div class="kpi-number" data-kpi="${k}">${fmt(k,t[k])}</div><div class="kpi-sub">${subs[k]}</div></div>`).join('')}</div>`;}
function rankList(rows){const max=Math.max(1,...rows.map(r=>Math.abs(r.profit)));return rows.slice(0,5).map((r,i)=>`<div class="rank-row"><div class="rank-number">${r.days?String(i+1).padStart(2,'0'):'—'}</div><div><button class="text-button rank-name" data-detail="${esc(r.id)}">${esc(r.name)}</button><div class="rank-bar"><i style="width:${r.days?Math.max(2,Math.abs(r.profit)/max*100):0}%;${r.profit<0?'background:#d99390':''}"></i></div></div><div class="rank-value ${r.profit<0?'negative':''}">${r.days?yen(r.profit):'未入力'}<small>${r.days?'ROAS '+pct(r.roas):'実績を入力してください'}</small></div></div>`).join('');}
function trend(){const rows=filtered();if(!rows.length)return '<p class="muted">日別実績を入力すると、利益の推移を表示します。</p>';let [a,b]=range();const dates=rows.map(r=>r.date).sort();a=a==='2000-01-01'?dates[0]:a;b=b==='2099-12-31'?dates.at(-1):b;a=[a,C.shift(b,-13)].sort().at(-1);const points=[];for(let d=a;d<=b;d=C.shift(d,1)){const rs=rows.filter(r=>r.date===d);points.push({date:d,has:rs.length>0,value:C.sum(rs).profit});}const max=Math.max(1,...points.map(p=>Math.abs(p.value)));return `<div class="table-wrap"><div class="trend">${points.map(p=>`<div class="trend-col" title="${p.date}: ${p.has?yen(p.value):'未入力'}"><i class="${!p.has?'missing':p.value<0?'loss':''}" style="height:${p.has?Math.max(2,Math.abs(p.value)/max*110):2}px"></i><span>${p.date.slice(5).replace('-','/')}</span></div>`).join('')}</div></div><p class="table-note">選択期間の末尾最大14日。棒の高さは利益の絶対額、赤は赤字。薄灰線は未入力。正確な金額は「日別実績」で確認できます。</p>`;}
function dashboard(){if(!data.lps.length)return empty('最初のLPから、改善の記録を。','LPを登録 → 日別実績を入力 → 修正したら変更履歴を追加。<br>どの変更のあとに成績が動いたかを、ひと目で確認できます。');const t=C.sum(filtered()),r=totalsByLP().sort((a,b)=>(b.days?1:0)-(a.days?1:0)||b.profit-a.profit);const changes=data.versions.filter(v=>(!$('#lp-filter').value||v.lpId===$('#lp-filter').value)&&v.date<=C.today()).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4);return kpis(t)+`<div class="split"><section class="panel"><div class="panel-head"><div><h2>利益ランキング</h2><p class="muted">${r.length} LP · 選択期間の成績</p></div><button class="text-button" data-action="ranking">すべて比較 →</button></div>${rankList(r)}</section><section class="panel"><div class="panel-head"><div><h2>最近の変更</h2><p class="muted">公開済みのバージョン履歴</p></div><span class="badge">CHANGE LOG</span></div>${changes.map(v=>`<div class="timeline-item"><div class="muted">${v.date} · ${esc(v.label)}</div><button class="text-button" data-detail="${esc(v.lpId)}">${esc(lpName(v.lpId))} →</button><p>${esc(v.note.length>85?v.note.slice(0,85)+'…':v.note)}</p></div>`).join('')||'<p class="muted">まだ公開済みのLPがありません。</p>'}</section></div><section class="panel"><div class="panel-head"><h2>日別の利益推移</h2><span class="badge gray">DAILY PROFIT</span></div>${trend()}</section>${formulas()}`;}
function formulas(){return `<details class="panel"><summary>指標の計算方法・入力のルール</summary><div class="formula-list"><p><strong>利益</strong>売上 − 広告費 − その他費用</p><p><strong>ROAS</strong>売上 ÷ 広告費 × 100</p><p><strong>送客単価 / 成果単価（CPA）</strong>広告費 ÷ 送客数 / 広告費 ÷ 成果数</p><p><strong>CVR / 送客率</strong>成果数 ÷ クリック数 × 100 / 送客数 ÷ クリック数 × 100</p><p><strong>クリック単価 / 送客後成約率</strong>広告費 ÷ クリック数 / 成果数 ÷ 送客数 × 100</p><p><strong>合計から再計算</strong>率や単価の単純平均は使いません。分母0は「—」。</p><p><strong>日別実績は手入力</strong>1日・1LPにつき1件。媒体別の数値を合算して入力します。自動取得やCRM連携はありません。</p><p><strong>成果と売上の計上</strong>成果の確定基準と計上日をLP間で統一してください。実績0の日も0で登録すると比較できます。</p></div></details>`;}
function lpPage(){if(!data.lps.length)return empty('LPを登録しましょう','LP名・URL・担当者・初版情報をまとめて管理します。');const list=data.lps.filter(l=>l.name.toLowerCase().includes(search.toLowerCase())&&(!$('#lp-filter').value||l.id===$('#lp-filter').value));const sums=totalsByLP();return `<div class="searchbar"><input id="lp-search" aria-label="LP名を検索" placeholder="LP名で検索" value="${esc(search)}"><span class="muted">${list.length} LP</span></div><div class="lp-grid">${list.map(l=>{const vs=C.versions(data,l.id),v=C.versionAt(data,l.id,C.today())||vs[0],s=sums.find(x=>x.id===l.id)||C.sum([]);return `<article class="lp-card"><span class="badge">${esc(v.label)}</span> <span class="muted">${vs.length}件の履歴${v.date>C.today()?' · 公開予定':''}</span><h2>${esc(l.name)}</h2><a class="url" href="${esc(v.url)}" target="_blank" rel="noopener noreferrer">${esc(v.url)} ↗</a><div class="lp-meta"><span>担当 ${esc(v.owner)}</span><span>公開 ${v.date}</span></div><div class="mini-kpis"><div><span>送客数</span><strong>${num(s.visits)}</strong></div><div><span>CVR</span><strong>${pct(s.cvr)}</strong></div><div><span>利益</span><strong class="${s.profit<0?'negative':''}">${yen(s.profit)}</strong></div></div><div class="card-actions"><button class="primary" data-detail="${esc(l.id)}">変更履歴・分析 →</button><button data-record-lp="${esc(l.id)}">実績を入力</button><button data-edit-lp="${esc(l.id)}">名前を編集</button><button class="danger" data-delete-lp="${esc(l.id)}">削除</button></div></article>`;}).join('')}</div>${!list.length?'<p class="muted">一致するLPはありません。</p>':''}`;}
function detailPage(){const l=data.lps.find(x=>x.id===selected);if(!l){view='lps';return lpPage();}const vs=C.versions(data,l.id);if(!vs.some(v=>v.id===selectedVersion))selectedVersion=vs.filter(v=>v.date<=C.today()).at(-1)?.id||vs[0].id;const v=vs.find(x=>x.id===selectedVersion),c=C.comparison(data,l.id,v.id,windowDays);return `<div class="panel-head"><button data-action="lps">← LP一覧</button><button class="primary" data-add-version="${esc(l.id)}">＋ 変更履歴を追加</button></div><section class="panel"><div class="panel-head"><div><h2>${esc(l.name)}</h2><p class="muted">修正前後の成績比較</p></div><span class="badge">BEFORE / AFTER</span></div><div class="comparison-controls"><label>比較する変更<select id="version-select">${vs.slice().reverse().map(v=>`<option value="${esc(v.id)}" ${v.id===selectedVersion?'selected':''}>${esc(v.label)} · ${v.date}</option>`).join('')}</select></label><label>比較日数の上限<select id="compare-window">${[7,14,30].map(n=>`<option value="${n}" ${windowDays===n?'selected':''}>前後${n}日</option>`).join('')}</select></label></div><p class="change-note">${esc(v.note)}</p><div class="lp-meta"><span>担当 ${esc(v.owner)}</span><a href="${esc(v.url)}" target="_blank" rel="noopener noreferrer">このバージョンのURL ↗</a></div>${c.available?`<p class="table-note">変更前 ${c.beforeStart}〜${c.beforeEnd} → 変更後 ${c.afterStart}〜${c.afterEnd}（各${c.n}日）<br>入力済み：前 ${c.before.days}/${c.n}日 · 後 ${c.after.days}/${c.n}日</p>${!c.complete?'<div class="alert">比較データ不足：未入力の日があります。以下は入力済み分の合計です。全日入力されるまで改善・悪化の判定は表示しません。</div>':'<p class="muted">同じ日数・両期間の全日入力を確認済みです。</p>'}<div class="metric-grid">${['cpv','cvr','profit','roas','visits','conversions','spend','revenue','cpa'].map(k=>compareMetric(k,c)).join('')}</div>`:`<div class="notice">${c.reason}</div>`}<p class="table-note">各バージョンの期間をまたがないよう同じ日数に短縮し、今日の途中データは比較から除外します。<br>変化は修正との因果関係を証明するものではありません。曜日・広告配信・流入の違いも合わせて確認してください。</p></section><section class="panel"><h2>変更履歴</h2><p class="muted">変更日以降の実績を、そのバージョンに自動で紐付けます。</p><div class="history">${vs.slice().reverse().map(v=>{const rr=data.records.filter(r=>r.lpId===l.id&&C.versionAt(data,l.id,r.date)?.id===v.id),s=C.sum(rr);return `<article class="timeline-item"><div class="history-head"><div><h3>${esc(v.label)} <span class="badge gray">${v.date>C.today()?'公開予定':v.date}</span></h3><span class="muted">担当 ${esc(v.owner)}</span></div><div><button class="text-button" data-edit-version="${esc(v.id)}">訂正</button>${v.id!==vs[0].id?` <button class="text-button danger" data-delete-version="${esc(v.id)}">削除</button>`:''}</div></div><p>${esc(v.note)}</p><a class="muted" href="${esc(v.url)}" target="_blank" rel="noopener noreferrer">URLを開く ↗</a><p class="muted">全期間の実績 ${rr.length}日 · 送客 ${num(s.visits)} · CVR ${pct(s.cvr)} · 利益 ${yen(s.profit)}</p></article>`;}).join('')}</div></section>`;}
function compareMetric(k,c){const a=c.before[k],b=c.after[k],change=a===null||b===null?null:b-a,low=['cpv','cpa'].includes(k),judge=['cpv','cpa','cvr','roas','profit'].includes(k);let label='比較データ不足',cls='';if(c.complete){if(change===null)label='分母0のため比較できません';else if(change===0)label='変化なし';else{const direction=change>0?'+':'−',amount=fmt(k,Math.abs(change)),suffix=['cvr','roas'].includes(k)?' pt':a===0?'':` (${change>0?'+':'−'}${(Math.abs(change)/Math.abs(a)*100).toFixed(1)}%)`;label=direction+amount.replace('%','')+suffix;if(judge){const good=low?change<0:change>0;cls=good?'good':'bad';label=(good?'改善 ':'悪化 ')+label;}}}return `<div class="compare-metric"><h3>${metricLabels[k]}</h3><div class="compare-values"><span>${fmt(k,a)}</span><span>→</span><strong>${fmt(k,b)}</strong></div><span class="delta ${cls}">${label}</span></div>`;}
function rankingPage(){if(!data.lps.length)return empty('LPごとの成績を比較','LPと実績を登録すると、比較表とランキングが表示されます。');const rows=ranked(),keys=['profit','spend','clicks','visits','conversions','revenue','cpv','cpa','cvr','roas'];return `<section class="panel"><div class="panel-head"><div><h2>LP比較・ランキング</h2><p class="muted">${['cpv','cpa','cpc'].includes(rankMetric)?'低い順':'高い順'} · 未入力・算出不可は順位対象外</p></div><label>並び替え<select id="rank-metric">${keys.map(k=>`<option value="${k}" ${k===rankMetric?'selected':''}>${metricLabels[k]}</option>`).join('')}</select></label><button data-action="csv-summary">比較CSV</button></div><div class="table-wrap"><table><thead><tr><th>順位 / LP名</th><th>入力日数</th>${keys.map(k=>`<th>${metricLabels[k]}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><td><span class="badge gray">${r.days&&r[rankMetric]!==null?i+1:'—'}</span> <button class="text-button" data-detail="${esc(r.id)}">${esc(r.name)}</button></td><td>${r.days}日</td>${keys.map(k=>`<td class="${k==='profit'&&r[k]<0?'negative':''}">${r.days?fmt(k,r[k]):'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="table-note">同じ集計期間で比較しますが、入力日数や配信量の差は揃えていません。各LPの入力日数もご確認ください。合計・率は入力済みの実績のみから算出します。</p></section>${formulas()}`;}
function recordsPage(){const rows=filtered().sort((a,b)=>b.date.localeCompare(a.date)||lpName(a.lpId).localeCompare(lpName(b.lpId)));return `<section class="panel"><div class="panel-head"><div><h2>日別実績 <span class="badge gray">${rows.length}件</span></h2><p class="muted">1日・1LPにつき1件。バージョンは公開日から自動判定。</p></div><button data-action="csv-records">実績CSV</button></div>${!rows.length?'<div class="empty"><p>この期間の実績はまだありません。</p><button class="primary" data-action="add-record">＋ 実績を入力</button></div>':`<div class="table-wrap"><table><thead><tr><th>日付 / LP</th><th>バージョン</th>${['spend','clicks','visits','conversions','revenue','other','profit'].map(k=>`<th>${metricLabels[k]}</th>`).join('')}<th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.date}<br><strong>${esc(lpName(r.lpId))}</strong></td><td>${esc(C.versionAt(data,r.lpId,r.date)?.label)}</td>${['spend','clicks','visits','conversions','revenue','other','profit'].map(k=>{const v=k==='profit'?r.revenue-r.spend-r.other:r[k];return `<td class="${k==='profit'&&v<0?'negative':''}">${fmt(k,v)}</td>`;}).join('')}<td><button data-edit-record="${esc(r.id)}">編集</button> <button data-copy-record="${esc(r.id)}">複製</button> <button class="danger" data-delete-record="${esc(r.id)}">削除</button></td></tr>`).join('')}</tbody></table></div>`}</section>`;}
function backupPage(){return `<div class="split"><section class="panel"><h2>バックアップを保存</h2><p class="muted">LP情報・変更履歴・日別実績をまとめてJSONファイルに保存します。別の端末ではこのファイルを復元して利用できます。</p><p><span class="badge">${data.lps.length} LP</span> <span class="badge gray">${data.versions.length} 履歴</span> <span class="badge gray">${data.records.length} 実績</span></p><button class="primary" data-action="export" ${demo?'disabled':''}>バックアップを書き出す</button>${blocked?'<p><button data-action="raw-export">読み込めない元データを保存</button></p>':''}<p class="table-note"><a href="lp-note-v1.zip" download>アプリ本体のZIPをダウンロード</a><br>ZIPには入力データは含まれません。</p></section><section class="panel"><h2>バックアップから復元</h2><p class="muted">復元は現在のデータをすべて置き換えます。先に現在のバックアップを保存してください。LP NoteのJSONにのみ対応します。</p><label class="file-label">JSONファイルを選択<input type="file" id="import-file" accept=".json,application/json" ${demo?'disabled':''}></label></section></div><section class="panel"><h2>保存について</h2><p class="muted">このブラウザ内だけに保存されます。ログイン・サーバー保存・自動同期はありません。ブラウザのデータ削除やプライベートブラウズの終了で消える場合があります。<br>既存CRMやAd Noteのデータを読み書きすることはありません。初版は広告媒体との自動連携を行わず、日別の数値を入力する方式です。</p></section>${formulas()}`;}
function render(){data=demo?data:actual;$('#demo-banner').hidden=!demo;$('#demo-toggle').textContent=demo?'実データに戻る':'サンプルを見る';const old=$('#lp-filter').value;$('#lp-filter').innerHTML='<option value="">すべてのLP</option>'+data.lps.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('');if(data.lps.some(l=>l.id===old))$('#lp-filter').value=old;const titles={dashboard:['OVERVIEW','ダッシュボード','LPの変化を、成果につなげる。'],lps:['LANDING PAGES','LP・変更履歴','LPと担当者、公開バージョンをひとつに。'],detail:['CHANGE ANALYSIS','変更前後の分析','どの修正のあとに、数字が変わったか。'],records:['DAILY RECORDS','日別実績','毎日の数字を、次の改善のヒントに。'],ranking:['PERFORMANCE','比較・ランキング','成果の出ているLPを見つける。'],backup:['YOUR DATA','バックアップ','大切な記録を、手元に残す。']};const tt=titles[view];$('#eyebrow').textContent=tt[0];$('#page-title').textContent=tt[1];$('#page-subtitle').textContent=tt[2];document.querySelectorAll('[data-nav]').forEach(b=>{const active=b.dataset.nav===(view==='detail'?'lps':view);b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false');});$('#filters').hidden=['backup','detail'].includes(view);const [a,b]=range(),bad=!C.day(a)||!C.day(b)||a>b;$('#filter-error').hidden=!bad||$('#filters').hidden;$('#range-label').textContent=$('#period').value==='all'?'全期間 · 入力済みデータ':`${a} 〜 ${b}`;document.querySelectorAll('.custom-date').forEach(x=>x.hidden=$('#period').value!=='custom');$('#content').innerHTML=({dashboard, lps:lpPage,detail:detailPage,records:recordsPage,ranking:rankingPage,backup:backupPage}[view])();document.querySelectorAll('[data-action="add-lp"],[data-action="add-record"],[data-add-version],[data-edit-lp],[data-edit-version],[data-delete-version],[data-delete-lp],[data-record-lp],[data-edit-record],[data-copy-record],[data-delete-record]').forEach(x=>x.disabled=demo||blocked);}
function navigate(v){view=v;render();window.scrollTo({top:0});}
function input(name,label,value='',type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function lpOptions(value){return data.lps.map(l=>`<option value="${esc(l.id)}" ${l.id===value?'selected':''}>${esc(l.name)}</option>`).join('');}
function versionFields(v){return `${input('label','バージョン *',v.label||'v1.0','text','required maxlength="60" placeholder="例：v1.1"')}${input('owner','担当者 *',v.owner||'','text','required maxlength="100"')}${input('date','公開日（適用日） *',v.date||C.today(),'date','required min="2000-01-01" max="2099-12-31"')}<label class="wide">URL *<input name="url" type="url" required maxlength="2000" value="${esc(v.url||'')}" placeholder="https://example.com/lp/"></label><label class="wide">変更した内容 *<textarea name="note" required maxlength="2000" placeholder="何を変更したか、狙いも残しましょう。">${esc(v.note||'')}</textarea></label>`;}
function openForm(type,id='',lpId=''){
  if(demo||blocked)return;
  if(type==='record'&&!data.lps.length){toast('先にLPを登録してください。');openForm('lp');return;}
  formState={type,id,lpId};let fields='',title='';
  if(type==='lp'){title='LPを登録';fields=input('name','LP名 *','','text','required maxlength="100"')+versionFields({note:'初版公開。'});}
  if(type==='lp-name'){title='LP名を編集';fields=input('name','LP名 *',lpName(id),'text','required maxlength="100"');}
  if(type==='version'){const old=data.versions.find(v=>v.id===id),latest=C.versions(data,lpId).at(-1);title=old?'変更履歴を訂正':'変更履歴を追加';fields=versionFields(old||{url:latest.url,owner:latest.owner,label:'',date:C.today(),note:''});if(!old)fields=fields.replace('value="v1.0"','value=""');}
  if(type==='record'||type==='copy'){const r=data.records.find(r=>r.id===id)||{lpId:lpId||selected||data.lps[0]?.id,date:C.today(),spend:'',clicks:'',visits:'',conversions:'',revenue:'',other:0,memo:''};if(type==='copy')formState.id='';title=type==='copy'?'実績を複製':id?'日別実績を編集':'日別実績を入力';fields=`<label>LP *<select name="lpId" required>${lpOptions(r.lpId)}</select></label>${input('date','日付 *',type==='copy'?C.today():r.date,'date',`required min="2000-01-01" max="${C.today()}"`)}<p id="version-preview" class="form-tip wide"></p>${C.FIELDS.map(k=>input(k,metricLabels[k]+' *',r[k],'number',`required min="0" step="1" max="${['clicks','visits','conversions'].includes(k)?1e9:1e10}" inputmode="numeric"`)).join('')}<div class="profit-preview wide" id="profit-preview">利益 —</div><label class="wide">メモ<textarea name="memo" maxlength="1000">${esc(r.memo)}</textarea></label>`;}
  $('#editor-title').textContent=title;$('#form-fields').innerHTML=`<p class="form-tip">${['record','copy'].includes(type)?'日別の合計を入力します。未入力の日と実績0の日を区別するため、必須欄は0も入力してください。金額は円。':type==='lp-name'?'名前の変更は過去の表示にも反映されます。':'同じLPの公開日は1日1バージョンです。変更日は当日0時から適用され、同日を含む実績の紐付けが更新されます。'}</p><div class="form-grid">${fields}</div>`;$('#entry-error').textContent='';$('#editor').showModal();$('#entry-form input, #entry-form select')?.focus();updatePreview();initialForm=JSON.stringify([...new FormData($('#entry-form')).entries()]);
}
function updatePreview(){if(!['record','copy'].includes(formState?.type))return;const f=$('#entry-form'),n=k=>Number(f.elements[k].value),p=n('revenue')-n('spend')-n('other');$('#profit-preview').textContent='利益 '+yen(p)+' = 売上 − 広告費 − その他費用';$('#profit-preview').classList.toggle('negative',p<0);const v=C.versionAt(data,f.elements.lpId.value,f.elements.date.value);$('#version-preview').textContent=v?'自動紐付け：'+v.label+'（'+v.date+' 公開）':'この日付に公開済みのバージョンがありません。';}
let initialForm='';$('#editor').addEventListener('close',()=>{formState=null;});
async function closeForm(){if(!$('#editor').open)return;const dirty=JSON.stringify([...new FormData($('#entry-form')).entries()])!==initialForm;if(dirty&&!await confirmAction('入力中の内容を破棄して閉じますか？','未保存の入力'))return;$('#editor').close();}
$('#editor-close').onclick=closeForm;$('#editor-cancel').onclick=closeForm;$('#editor').addEventListener('cancel',e=>{e.preventDefault();closeForm();});$('#entry-form').addEventListener('input',updatePreview);
$('#entry-form').addEventListener('submit',async e=>{
  e.preventDefault();const button=$('#entry-form [type="submit"]');button.disabled=true;$('#entry-error').textContent='';
  try{const values=Object.fromEntries(new FormData(e.target)),next=clone(),s=formState;for(const k of Object.keys(values))values[k]=values[k].trim();
    if(s.type==='lp'){const lpId=uid();next.lps.push({id:lpId,name:values.name});const {name,...version}=values;next.versions.push({id:uid(),lpId,...version});selected=lpId;}
    if(s.type==='lp-name'){next.lps.find(l=>l.id===s.id).name=values.name;}
    if(s.type==='version'){const existing=next.versions.find(v=>v.id===s.id),item={id:s.id||uid(),lpId:s.lpId,...values};if(existing)Object.assign(existing,item);else next.versions.push(item);C.validate(next);const changed=actual.records.filter(r=>r.lpId===s.lpId&&C.versionAt(actual,r.lpId,r.date)?.id!==C.versionAt(next,r.lpId,r.date)?.id).length;if(changed&&!await confirmAction(`${changed}件の既存実績が公開日に従って別バージョンへ紐付きます。変更履歴を保存しますか？`,'実績の紐付けが変わります'))return;selectedVersion=item.id;}
    if(['record','copy'].includes(s.type)){const record={id:s.id||uid(),lpId:values.lpId,date:values.date,memo:values.memo,...Object.fromEntries(C.FIELDS.map(k=>[k,Number(values[k])]))},index=next.records.findIndex(r=>r.id===record.id);if(index>=0)next.records[index]=record;else next.records.push(record);}
    await save(next);$('#editor').close();toast('保存しました。');
  }catch(err){$('#entry-error').textContent=err.message;}finally{button.disabled=false;}
});
function download(name,body,type){const u=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),10000);}
function exportBackup(){if(demo||blocked){toast('実データを読み込めないため、通常の書き出しはできません。');return;}download('lp-note-backup-'+C.today()+'.json',JSON.stringify(actual,null,2),'application/json');toast('バックアップを書き出しました。');}
const csvCell=v=>'"'+String(v??'').replace(/^[\s]*[=+@-]/,"'$&").replace(/"/g,'""')+'"';
function exportCSV(summary){const keys=summary?['spend','clicks','visits','conversions','revenue','other','profit','cpv','cpa','cvr','roas']:['spend','clicks','visits','conversions','revenue','other','profit'];let rows;if(summary){rows=[['LP名','入力日数',...keys.map(k=>metricLabels[k])],...ranked().map(r=>[r.name,r.days,...keys.map(k=>r.days?r[k]:'')])];}else{rows=[['日付','LP名','バージョン',...keys.map(k=>metricLabels[k]),'メモ'],...filtered().sort((a,b)=>a.date.localeCompare(b.date)).map(r=>[r.date,lpName(r.lpId),C.versionAt(data,r.lpId,r.date)?.label,...keys.map(k=>k==='profit'?r.revenue-r.spend-r.other:r[k]),r.memo])];}download('lp-note-'+(summary?'comparison':'records')+'-'+C.today()+'.csv','\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
async function importFile(file){if(!file||demo)return;try{if(file.size>8*1024*1024)throw Error('8MB以下のJSONファイルを選択してください。');const next=C.validate(JSON.parse(await file.text()));if(!await confirmAction(`LP ${next.lps.length}件・履歴 ${next.versions.length}件・実績 ${next.records.length}件を復元します。\n現在のデータはすべて置き換わります。バックアップは保存しましたか？`,'バックアップを復元'))return;await save(next,true);toast('バックアップを復元しました。');}catch(e){toast('復元できません：'+e.message);}finally{if($('#import-file'))$('#import-file').value='';}}
function toggleDemo(){demo=!demo;data=demo?C.sample():actual;selected='';selectedVersion='';$('#lp-filter').value='';if(demo){$('#period').value='all';}else load();view='dashboard';render();}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;try{
  if(d.nav)navigate(d.nav);
  if(d.detail){selected=d.detail;selectedVersion='';navigate('detail');}
  if(d.action==='add-lp')openForm('lp');
  if(d.action==='add-record')openForm('record','',$('#lp-filter').value||'');
  if(d.action==='demo')toggleDemo();
  if(['lps','ranking'].includes(d.action))navigate(d.action);
  if(d.deleteLp){const count=actual.records.filter(r=>r.lpId===d.deleteLp).length;if(await confirmAction(`「${lpName(d.deleteLp)}」と全変更履歴・実績${count}件を削除します。元に戻せません。必要なバックアップを先に保存してください。`,'LPを削除')){const next=clone();next.lps=next.lps.filter(l=>l.id!==d.deleteLp);next.versions=next.versions.filter(v=>v.lpId!==d.deleteLp);next.records=next.records.filter(r=>r.lpId!==d.deleteLp);await save(next);toast('LPと関連データを削除しました。');}}
  if(d.deleteVersion){const v=actual.versions.find(v=>v.id===d.deleteVersion);if(v.id===C.versions(actual,v.lpId)[0].id)throw Error('初版は削除できません。');const count=actual.records.filter(r=>r.lpId===v.lpId&&C.versionAt(actual,r.lpId,r.date)?.id===v.id).length;if(await confirmAction(`変更履歴「${v.label}」を削除します。実績${count}件は削除せず、前のバージョンに紐付け直します。`,'変更履歴を削除')){const next=clone();next.versions=next.versions.filter(x=>x.id!==v.id);await save(next);toast('変更履歴を削除しました。');}}
  if(d.editLp)openForm('lp-name',d.editLp);
  if(d.addVersion)openForm('version','',d.addVersion);
  if(d.editVersion){const v=data.versions.find(v=>v.id===d.editVersion);openForm('version',v.id,v.lpId);}
  if(d.recordLp)openForm('record','',d.recordLp);
  if(d.editRecord)openForm('record',d.editRecord);
  if(d.copyRecord)openForm('copy',d.copyRecord);
  if(d.deleteRecord){const r=actual.records.find(r=>r.id===d.deleteRecord);if(await confirmAction(`${r.date}「${lpName(r.lpId)}」の実績1件を削除します。この操作は取り消せません。`,'日別実績を削除')){const next=clone();next.records=next.records.filter(x=>x.id!==r.id);await save(next);toast('実績を削除しました。');}}
  if(d.action==='export')exportBackup();
  if(d.action==='raw-export')download('lp-note-recovery.txt',raw||'','text/plain');
  if(d.action==='csv-records')exportCSV(false);
  if(d.action==='csv-summary')exportCSV(true);

}catch(err){toast(err.message);}});
document.addEventListener('change',e=>{if(['period','start','end','lp-filter'].includes(e.target.id))render();if(e.target.id==='rank-metric'){rankMetric=e.target.value;render();}if(e.target.id==='version-select'){selectedVersion=e.target.value;render();}if(e.target.id==='compare-window'){windowDays=Number(e.target.value);render();}if(e.target.id==='import-file')importFile(e.target.files[0]);});
document.addEventListener('input',e=>{if(e.target.id==='lp-search'){const pos=e.target.selectionStart;search=e.target.value;render();$('#lp-search').focus();$('#lp-search').setSelectionRange(pos,pos);}});
$('#demo-toggle').onclick=toggleDemo;$('#demo-exit').onclick=toggleDemo;
window.addEventListener('storage',e=>{if((e.key===KEY||e.key===null)&&!demo){$('#storage-alert').hidden=false;$('#storage-alert').textContent='別タブでデータが変更されました。古い内容の上書きを防ぐため、再読み込みしてください。';blocked=true;render();}});
$('#start').value=C.today().slice(0,7)+'-01';$('#end').value=C.today();load();render();
